[[encoding_rules]]
[obligation=informative]
== UML to JSON encoding rules

The CRS JSON text is a representation of the definition of a CRS or coordinate operation.
A text describes one CRS or coordinate operation object.
Each object is represented by a set of tokens comprised of a name followed by a value, the set enclosed by curly brackets.
Some name/value pairs (or members) are themselves other JSON objects, thus resulting in a nested structure.
The names and the value types are derived from two sources:

* The schema of metadata objects (`Identifier`, `Citation`, `Extent`, `PositionalAccuracy`)
  is taken verbatim from <<ISO19115-4>>.
* The schema of other objects is derived from <<ISO19111>> UML
  by application of the rules defined in <<OGC24-017>>.

<<OGC24-017>> covers three categories of JSON encoding:
plain JSON, GeoJSON compliant and JSON-FG compliant.
This standard uses plain JSON encoding.


[[number]]
=== Number

Best practice is to preserve the original precision as specified by the information source.
This may require maintaining 16 digits of precision.


[[date]]
=== Date and time

Calendar dates and times are restricted to the Gregorian calendar and the 24-hour clock as defined in ISO 8601-1.
Only the ISO 8601-1 extended format (separators between date units and between sexagesimal time units) is permitted.
Any precision is allowed. When time is included a UTC or local time zone designator is required.
In ISO 8601-1 time zone designator may be omitted, in which case local time is assumed but unspecified.
In this document a time zone designator is mandatory.
Examples:

.Date and time examples
|=====
|2014                      | (Precision = year)
|2014-01                   | (Calendar date, precision = month)
|2014-03-01                | (Calendar date, precision = day)
|2014-060                  | (Ordinal date, precision = day)
|2014-05-06T23Z            | (Calendar date, precision = hour, UTC)
|2014-157T23Z              | (Ordinal date, precision = hour, UTC)
|2014-07-12T16:00Z         | (Precision = minute, UTC)
|2014-07-12T17:00+01       | (Precision = minute, local time one hour ahead of UTC)
|2014-09-18T08:17:56-08    | (Precision = second, local time eight hours behind UTC)
|2014-11-23T00:34:56.789Z  | (Precision = 1/1000 second, UTC)
|=====


[[extent]]
=== Extent

Extent describes the spatial and/or temporal applicability of a CRS, datum, datum ensemble or coordinate operation.
Extent in this document uses the concepts described in <<ISO19115-1>>.
It allows for horizontal, vertical and temporal extents.
The extent contains the following attributes:

The `description` is an optional attribute which describes the geographic area by a character string.
Example:

.Geographic description example
[source,json]
----
"domainOfValidity": [
  {
    "description": "Netherlands offshore."
  }
]
----

The `geographicElement` is an optional attribute which describes the horizontal extent.
If present, the value should be an object of type `EX_GeographicBoundingBox`.
The geographic bounding box describes a "north up" area.
Upper right latitude will be greater than the lower left latitude.
Generally the upper right longitude will be greater than the lower left longitude.
However when the area crosses the 180° meridian,
the value of the lower left longitude will be greater than the value of the upper right longitude.
The geographic bounding box is an approximate description of location.
For most purposes a coordinate precision of two decimal places of a degree is sufficient.
At this resolution the identification of the geodetic CRS to which the bounding box coordinates are referenced is not required.

.Geographic bounding box example
[source,json]
----
"domainOfValidity": [
  {
    "geographicElement": [
      {
        "entityType": "EX_GeographicBoundingBox",
        "westBoundLongitude":  2.54,
        "eastBoundLongitude":  6.40,
        "southBoundLatitude": 51.43,
        "northBoundLatitude": 55.77
      }
    ]
  }
]
----

The `verticalElement` is an optional attribute which describes a height range over which a CRS or coordinate operation is applicable.
Depths have negative height values.
Vertical extent is an approximate description of location;
heights are relative to an unspecified mean sea level.
