.Preface

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies).
The work of preparing International Standards is normally carried out through ISO technical committees.
Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee.
International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work.
ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards.
Draft International Standards adopted by the technical committees are circulated to the member bodies for voting.
Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights.
ISO shall not be held responsible for identifying any or all such patent rights.
////

[[abstract]]
[abstract]
== Abstract

This Standard defines the structure and content of JSON documents describing coordinate reference systems (CRSs)
and coordinate operations between coordinate reference systems.
It does not prescribe how implementations should read or write these documents.
This Standard follows the provisions of ISO 19111:2019 including its amendments 1 and 2.

[[preface]]
== Preface

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
====

[[security]]
== Security considerations

No security considerations have been made for this Standard.

[[submitters]]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name*              |*Affiliation*
|Keith Ryden         |ESRI
|Martin Desruisseaux |Geomatys
|===

////
NOTE: Uncomment if necessary
== Contributors

Additional contributors to this Standard include the following:

Individual name(s), Organization
////
