.Preface

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies).
The work of preparing International Standards is normally carried out through ISO technical committees.
Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee.
International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work.
ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards.
Draft International Standards adopted by the technical committees are circulated to the member bodies for voting.
Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights.
ISO shall not be held responsible for identifying any or all such patent rights.
////

[[abstract]]
[abstract]
== Abstract

This Standard defines the structure and content of JSON documents describing coordinate reference systems (CRSs)
and coordinate operations between coordinate reference systems.
It does not prescribe how implementations should read or write these documents.
This Standard follows the abstract model of <<ISO19111>> including its amendments 1 and 2 (also available as OGC Topic 2)
and the rules of <<OGC24-017>> for translating the model to a JSON encoding.

[[preface]]
== Preface

During the June 2022 OGC Member Meeting in Madrid (Spain),
the joint CRS DWG/SWG working groups approved a motion to work on the adoption of a JSON Schema for
Coordinate references to be defined in parallel with the CRS WKT Standard and derived from ISO 19111 and OGC Topic 2.
The group recognized the PROJ6 origins of the PROJJSON schema contribution being used as the starting point of this work.
Meanwhile, OGC aimed to come to a standardized encoding from UML to JSON,
in order to achieve technical interoperability in the chain from conceptual models to JSON implementation.
For example, CRS JSON contains metadata objects whose encoding is specified by <<ISO19115-4>>.
Following standardized rules help to keep a consistent encoding for all objects in a CRS JSON text.
The rules have been published in 2026 as <<OGC24-017>> and provides guidance for modeling aspects
needed by CRS JSON but having many possible JSON representations, such as:

* by-reference encoding of property values,
* JSON schema encoding for unions, and
* JSON schema encoding for code lists.

[[security]]
== Security considerations

A JSON text can be parsed by the `eval(…)` function of the JavaScript language.
While a text compliant with this Standard does not contain executable code,
a CRS definition compromised by an attacker could.
JavaScript applications should parse CRS JSON texts with `JSON.parse(…)` or an equally safe function.

[[submitters]]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name*              |*Affiliation*
|Keith Ryden         |ESRI
|Martin Desruisseaux |Geomatys
|===

////
NOTE: Uncomment if necessary
== Contributors

Additional contributors to this Standard include the following:

Individual name(s), Organization
////
